{% set name = "sofa-cmake" %}

package:
  name: "{{ name }}"
  version: 1.0.0

source:
  git_url: https://github.com/tudat-team/sofa-cmake.git
  git_rev: fab8156a5ef1f873f46c0d2b5df0e048616a0a66

build:
  number: 2
  ignore_run_exports:
    - m2w64-gcc-libs  # [win]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}               # [not win]
    - {{ compiler('m2w64_c') }}         # [win]
    - m2w64-toolchain                   # [win]

about:
  home: https://github.com/tudat-team/sofa-cmake
  license: BSD
  license_family: BSD
  summary: Standards of Fundamental Astronomy code, copyright of the Board of the International Astronomical Union.
